packages:
    - yum-cron

runcmd:
    - [ systemctl, start, yum-cron ]
    - [ systemctl, enable, yum-cron ]

write_files:
    - path: /etc/yum/yum-cron.conf
      owner: root:root
      permissions: '0644'
      content: |
        [commands]
        update_cmd = default
        update_messages = no
        download_updates = yes
        apply_updates = yes
        random_sleep = 360

        [emitters]
        system_name = None
        emit_via = stdio
        output_width = 80

        [email]
        email_from = root@localhost
        email_to = root
        email_host = localhost

        [groups]
        group_list = None
        group_package_types = mandatory, default

        [base]
        debuglevel = -2
        # skip_broken = True
        mdpolicy = group:main
        # assumeyes = True

merge_type: 'list(append)+dict(recurse_array)+str()'
