#cloud-config

timezone: America/Chicago
fqdn: ${hostname}

packages:
    - git
    - ipset
    - ipset-service
    - iptables
    - iptables-services
    - jq
    - openldap-clients
    - mariadb
    - mariadb-devel
    - pv
    - python
    - python-devel
    - sssd
    - sudo
    - wget
    - vim

bootcmd:
    - [ cloud-init-per, once, pie-install-epel, amazon-linux-extras, install, epel ]
runcmd:
    - systemctl restart crond
    - yum install -y @development
    - systemctl enable iptables
    - systemctl start iptables
    - iptables -t filter -I OUTPUT 1 -p tcp -d 169.254.169.254 -j REJECT --reject-with icmp-admin-prohibited
    - iptables -t filter -I OUTPUT 1 -p tcp -d 169.254.169.254 -m owner --uid-owner 0-999 -j ACCEPT

ssh_pwauth: yes
repo_update: false
package_reboot_if_required: false

merge_type: 'list(append)+dict(recurse_array)+str()'
