#cloud-config

timezone: America/Chicago
fqdn: ${hostname}

packages:
    - git
    - ipset
    - ipset-service
    - iptables
    - iptables-services
    - jq
    - mariadb
    - mariadb-devel
    - pv
    - python
    - python-devel
    - sssd
    - sudo
    - wget
    - vim

bootcmd:
    - [ cloud-init-per, once, pie-install-epel, amazon-linux-extras, install, epel ]
    - [ cloud-init-per, once, pie-install-devel, yum, install, "-y", "@development", openssl-devel, pam-devel ]

ssh_pwauth: yes
repo_update: false
package_reboot_if_required: false

merge_type: 'list(append)+dict(recurse_array)+str()'
