#cloud-config

timezone: America/Chicago
fqdn: ${hostname}

packages:
    - at
    - cronie
    - git
    - ipset
    - ipset-service
    - iptables
    - iptables-services
    - jq
    - mariadb1011
    - openldap
    - openldap-clients
    - pv
    - python3
    - python3-boto3
    - python3-botocore
    - python3-dnf-plugin-post-transaction-actions
    - sssd
    - sudo
    - wget
    - vim

bootcmd:
    - [ cloud-init-per, once, bastion-install-devel, dnf, install, "-y", "@development", openssl-devel, pam-devel, mariadb1011-devel, openldap-devel, python3-devel ]

ssh_pwauth: yes
repo_update: false
package_reboot_if_required: false

merge_type: 'list(append)+dict(recurse_array)+str()'
